### ISSUE TITLE
建议做成npm包

### ISSUE THREAD

**Issue by Harbour8643** [Ctrl-Ling/XLSX-Style-Utils#3]
这个工具库做的还是很不错的，建议做成依赖xlsx包的npm包，这样方便使用

**Comment by Ctrl-Ling** [comment]
前端菜鸟，工作需要临时写得😂后期很闲的时候会考虑改

**Comment by Ctrl-Ling** [comment]
> 这个工具库做的还是很不错的，建议做成依赖xlsx包的npm包，这样方便使用

前端菜鸟，工作需要临时写得😂后期很闲的时候会考虑改
